name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run security scans
      run: |
        npm audit --audit-level=high
        npx eslint . --ext .js,.jsx,.ts,.tsx
        npx stylelint "**/*.{css,scss,sass}"
